### ISSUE TITLE
Probléme de clavier

### ISSUE THREAD

**Issue by pijalu** [pijalu/creaves#102]
Au début ça allait bien, mais embardée vers le milieu
![image](https://user-images.githubusercontent.com/1093797/124650422-054a0900-de9a-11eb-8afc-60e4b9fbd641.png)

**Comment by crealan** [comment]
probleme résolu via 258596

**Comment by pijalu** [comment]
![image](https://user-images.githubusercontent.com/1093797/124653490-a71f2500-de9d-11eb-84ca-b07082e6afd0.png)
Pas encore
