### ISSUE TITLE
creer un outils d'export des données

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#108]
Développer un outil d'export au format **xls** afin de régler les problèmes d'import et de caractère spéciaux.

Prévoir les 2 tableaux suivant:
1.  Outil d'export selon la date d'entrée comprise entre ou selon la date de sortie comprise entre sur le modèle du registre détail.
2.  Outil d'export animal présent à la date du selon le modèle suivant: Numéro, Espèce, Date d'admission, Zone, Cage, Age Identification. Avec la possibilité de sélectionner les zone interne et ou les zones externes.

**Comment by crealan** [comment]
Outil d'export animal présent à la date du selon le modèle de colonnes suivant: Numéro, Espèce, Date d'admission, Zone, Cage, Age Identification. Avec la possibilité de sélectionner les zone interne et ou les zones externes au centre.

![export animaux en cours de soin à la date](https://user-images.githubusercontent.com/80490183/216731888-c9c5cc84-a3e5-4fc3-b32e-077f831c8d63.png)

**Comment by pijalu** [comment]
test sur Muad
