### ISSUE TITLE
MAJ PROCES INTAKE DECEMBRE 2023

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#113]
Dans https://creaves.muaddib.net/reception/new/

Prérequis:
fermer le ticket 165 Création de la table des Localités
fermer le ticket 143 Mettre à jour la table espèce

Étape 1: Remplir les informations sur l'animal:
- Retirer le type par défaut obligatoire afin de forcer la sélection du bon type. (déjà fait)
- Assigner une espèce par défaut au différents types d'animaux 
- Ajouter un pop up "espèce inconnue voulez-vous continuer" au clic sur suivant si l'espèces tapée n'est pas connue par la bdd champ creaves_species
- affiché les champs creaves group et gibier selon l'espèce encodée

Étape 2: Remplir des informations sur la découverte

Dans discoveries:
- Ajouter un champ code Postal et un champ village (proposition de la table Localité champ code postal et localité)
- ajouter une check box "l'animal trouvé dans le jardin du découvreur" et transposer les données des champs cp et village dans les données découvreur 
- Renommer le champ actuel "Lieu (village)" en "précision lieu"  (table discoveries "location') (ne plus rendre le champ obligatoire)
- Remonter le cadre Details Condition au dessus du découvreur réduire la taille du cadre de 1/2

Dans discoverers:
- Ajouter un autocomplète intelligent champ par champ pour le découvreur
- Ajouter un champ code postal (proposition de la table Localité champ code postal)
- Sur le champ ville ajouter la proposition de la table Localité champ Localité
- Ajouter un champ don en € 
- Compléter le Pays par défaut Belgique

- Ajouter une check box "Retour dans l'habitat"

Étape 3: Remplir les informations d'admission

- Remonter la sélection du nombre d'individus en haut de la page bloquer l'édition des champs général, blessures, parasites et remarques si plusieurs animaux sont sélectionner pour l'entrée
- Empêcher de terminer l'entrée si la date d'entrée est antérieur à la date de découverte
- Placer le focus sur le champ général et le renommer en "Etat général"
- remplacer le bouton blessures par "l'animal est il blessé" OUI ou NON avec ajout d'un "TRUE" / "FALSE" dans la bdd
- remplacer le bouton parasites par "l'animal est il parasité" OUI ou NON avec ajout d'un "TRUE" / "FALSE" dans la bdd
- réduire la taille des cadres de 1/2
- Ne plus rendre obligatoire le champ général

**Comment by crealan** [comment]
Retrait de:
- Proposer dans le champ espèce uniquement les espèces se réfèrent au type d'animaux 
Seras fais plus tard selon réelle utilité et éventuellement avec une ammonisation des animal type entre centre CREAVES.

**Comment by pijalu** [comment]
on muaddib

**Comment by crealan** [comment]
Modification à apporté au proces intake

![Capture d'écran 2023-12-19 211428](https://github.com/pijalu/creaves/assets/80490183/7c75bec7-d78f-4462-9417-a52e641d2eca)
![Capture d'écran 2023-12-19 205214](https://github.com/pijalu/creaves/assets/80490183/b8218030-3e05-426f-8294-3af8b269db62)
![Capture d'écran 2023-12-19 204954](https://github.com/pijalu/creaves/assets/80490183/f146b54f-7ab5-4102-b070-ad9109ffd650)
![Capture d'écran 2023-12-19 210835](https://github.com/pijalu/creaves/assets/80490183/a2800abb-a87b-4d45-9a12-06380b2fc71b)

**Comment by crealan** [comment]
Si possible proposer le code postal selon la localité tapée car le découvreur peut connaitre le village de découverte sans en connaitre le code postal.

![Capture d'écran 2023-12-19 220038](https://github.com/pijalu/creaves/assets/80490183/80644710-5d9e-48a7-8faa-e4d5a4100a3b)
