### ISSUE TITLE
Ajouter le champ selectionnable pour la cause d'entrée

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#116]
dans nouvelle réception à l'étape 2  (https://creaves.muaddib.net/reception/new/)
![image](https://github.com/user-attachments/assets/dc99fa39-ebd8-456a-bf64-08532d49a5c4)

**- créer la table Cause_entry il y as des causes principales des qu'elles dépende les causes secondaire**

**- Les données ne doivent pas pouvoir être modifiée par les CREAVES il n'est pas utile de crée une vue en admin**

**- ajouter le champ sélectionnable avec les causes d'entrée**
- La liste doit être fixe impossible d'encoder une donnée libre
- On encode la cause et la sous cause via un seul champ
- les causes doivent s'affichée dans l'ordre de la liste
- le champ doit être vide par défaut
- Il doit être possible de taper pour rechercher la bonne cause
- la cause d'entrée est un champ obligatoire
- la cause par défaut pour les données existante est "Indéterminé"

fichiers avec les données:
[Causes d'entrée validées par SPW_bdd_V1.xlsx](https://github.com/user-attachments/files/18204191/Causes.d.entree.validees.par.SPW_bdd_V1.xlsx)
[Causes d'entrée validées par SPW_bdd_V1.xlsx - BDD exemple2.csv](https://github.com/user-attachments/files/18204192/Causes.d.entree.validees.par.SPW_bdd_V1.xlsx.-.BDD.exemple2.csv)

**Comment by crealan** [comment]
[causes-entrée.xlsx](https://github.com/pijalu/creaves/files/10326261/causes-entree.xlsx)


NON IDENTIFIEE = par défaut et pour les entrée existante.

**Comment by crealan** [comment]
urgent

**Comment by crealan** [comment]
[causes entrée.ods](https://github.com/pijalu/creaves/files/10593476/causes.entree.ods)

NON IDENTIFIEE = par défaut et pour les entrée existante.

**Comment by crealan** [comment]
Table avec 5 colonnes (id, cause d'entrée, indication cause, Nature de la cause, Default)
NON IDENTIFIEE = par défaut et pour les entrée existante.

[causes.d.entree.09_02_23.-.Causes.csv](https://github.com/pijalu/creaves/files/11360129/causes.d.entree.09_02_23.-.Causes.csv)

**Comment by crealan** [comment]
Table avec 5 colonnes (id, cause d'entrée, indication cause, Nature de la cause, Default)
NON IDENTIFIEE = par défaut et pour les entrée existante.

[causes.d.entree.09_02_23.-.Causes.csv](https://github.com/pijalu/creaves/files/11368010/causes.d.entree.09_02_23.-.Causes.csv)

**Comment by crealan** [comment]
![image](https://github.com/user-attachments/assets/9af3ff10-bdf0-40b8-bfae-8741116dad3e)

**Comment by pijalu** [comment]
![image](https://github.com/user-attachments/assets/6d1d12b4-e570-499c-b9b2-291a79838a93)
