### ISSUE TITLE
creer l'instance creaves de jumet

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#118]
CREAVES de Jumet l'annexe des hérissons.
avec le domaine https://www.jumet.creaves.app/
merci d'envoyer l'ip

**Comment by pijalu** [comment]
IP: 129.151.68.173
Temp hosted at https://jumet.muaddib.net

**Comment by crealan** [comment]
Redirection non de domaine ok

**Comment by pijalu** [comment]
config updated
