### ISSUE TITLE
creer l'instance de birdsbay

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#120]
CREAVES de louvain la neuve birds bay.
avec le domaine https://www.birdsbay.creaves.app/
merci d'envoyer l'ip

**Comment by pijalu** [comment]
IP: 129.151.68.173
Temp hosted at https://bbay.muaddib.net

**Comment by crealan** [comment]
Redirection nom de domaine ok

**Comment by pijalu** [comment]
config updated
