### ISSUE TITLE
creer l'instance du CREAVES de Sprimont

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#122]
merci de creer l'instance pour le CREAVES de sprimont
avec le domaine https://www.sprimont.creaves.app/
La redirection du domaine est faite sur l'ip: 129.151.68.173

**Comment by pijalu** [comment]
DNS does not seems to exists

**Comment by crealan** [comment]
DNS ok

**Comment by pijalu** [comment]
Release done
