### ISSUE TITLE
Problème avec la numérotation! 

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#124]
La numérotation annuel samble fonctionné selon la date de création et non pas la date d'entrée! 
![num annu](https://user-images.githubusercontent.com/80490183/159804206-845c15fd-0588-43d0-b4df-808fb7bda7d9.png)

voir que faire si il est possible de recalculer les numéros annuel sur base des dates et heures d'entrée,

**Comment by pijalu** [comment]
Installed on test env - please confirm for a general deploy ;)

**Comment by crealan** [comment]
Go pour prod
