### ISSUE TITLE
creer l'instance du CREAVES de bousval

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#125]
merci de creer l'instance pour le CREAVES de bousval
avec le domaine https://www.bousval.creaves.app/   et  bousval.creaves.app
La redirection du domaine est faite sur l'ip: 129.151.71.48

**Comment by crealan** [comment]
![arche](https://user-images.githubusercontent.com/80490183/215339940-176a06fa-5dd8-4feb-b0a4-fae8320718e8.png)

**Comment by pijalu** [comment]
https://www.bousval.creaves.app/ created
