### ISSUE TITLE
problème de chargement des type d'animaux dans l'accueil travail impossible!!!

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#127]
Sur l'instance de virelle, en navigant entre type d'animaux il y as parfois aucune action. 

![image](https://user-images.githubusercontent.com/80490183/162067289-42570d3c-750c-4bde-a997-f36fc6b87cbd.png)

j'ai essayer de provoquer le problème sur muaddib sans aucun résultat! 
Un reboot du système est peut-etre nécéssaire.

**Comment by pijalu** [comment]
released - please retest
