### ISSUE TITLE
Ajout filtre et tri Animaux en cours de soins

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#129]
Ajout d'une possibilité de filtre sur animaux en cours de soins et dans animaux
Ajout d'un tri des colonnes (Numéro, Cage, Espèce, Age, Indentification Traitements)

![filtre tri animaux en c s](https://user-images.githubusercontent.com/80490183/171948935-1b86238b-01ca-435e-8696-7b43093b78e9.png)

**Comment by crealan** [comment]
-  l'ajouter sur: animals avec choix de tri sur animal sorti. 
- Serait il possible de faire une recherche ou un tri sur base de 1 caractère?
Exemple afficher les animaux en salle de soin la cage commence par S

**Comment by crealan** [comment]
![recherche](https://user-images.githubusercontent.com/80490183/209882384-49b00e74-74ad-4469-8e97-e8e9c1cd69e4.png)

**Comment by crealan** [comment]
N'est il pas possible de garder l'affiche de l'ensemble des animaux ? sauf si cela crée un problème de performance! ou afficher une valeur par défaut plus grande que 10.
![nombre](https://user-images.githubusercontent.com/80490183/209883880-7f77a893-4ffd-4c82-b49f-4365331e607f.png)

**Comment by pijalu** [comment]
check new update
