### ISSUE TITLE
creer l'instance du CREAVES de Souvret

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#132]
merci de créer l'instance pour le CREAVES de Souvret
avec le domaine https://www.souvret.creaves.app/ et souvret.creaves.app
La redirection du domaine est faite sur l'ip: 129.151.71.48

**Comment by crealan** [comment]
![soouvrt](https://user-images.githubusercontent.com/80490183/215339917-73cad817-2fb3-4eda-81bf-518bd67d2228.png)

**Comment by pijalu** [comment]
https://www.bousval.creaves.app/ created
