### ISSUE TITLE
Mise en place des Zones

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#134]
Créer une table contenant les différentes zones du centre afin de pouvoir y lier des cages et trier les animaux par zone.
Les zones externe au centre doivent clairement être identifiée (différence de couleurs de police ou autre) 

Table avec 4 colonnes (id, Zone, type de zone, Default)

[zone - zones.csv](https://github.com/pijalu/creaves/files/10701949/zone.-.zones.csv)

 dans la fiche de l'animal onglet général ajouter un champ zone a coter du champ cage

![zone](https://github.com/pijalu/creaves/assets/80490183/d6092fbf-c170-4ee0-82b4-9ca31ca4b614)

Si opportun:
Créer une table contenant les différentes cages du centre afin de pouvoir y lier des zones et proposer les cages lors de l'encodage selon la zone.
Table avec 3 colonnes (id, Cage, type, id_Zone)

**Comment by pijalu** [comment]
on muaddib

**Comment by crealan** [comment]
![Capture d'écran 2023-12-19 215037](https://github.com/pijalu/creaves/assets/80490183/c6838eef-0270-4b78-b72b-f33f59111369)

Il semble plus opportun d'avoir un select entre les 2 types de zones, car ces types ne sont pas censés évoluer, mais les zones seront créées et mises à jour par chaque creaves.

De plus, il faut prévoir une mise en avant des animaux qui sont dans des zones externes au centre (voir ticket 140).
