### ISSUE TITLE
Terminer la renumérotation

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#137]
Il faut terminer les endroits ou la renumérotation n'est pas correct.

- Retirer ID dans la fiche de l'animal (génère trop de confusion)
- Dans les templates de mise à jour des cares, veterinaryvisits, treatments, outtakes l'ID est toujours indiquer
- Sur la page dashboard dans le cadre Animaux avec traitements aujourd'hui il est toujours affiché **ID**

**Comment by pijalu** [comment]
on muad
