### ISSUE TITLE
Animaux en cours de soin par zone

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#140]
Ajouter la possibilité sur la vue animaux en cours de soin  (https://creaves.muaddib.net/) de trier les animaux par zone. 
Les zones externe au centre doivent clairement être identifiée (différence de couleurs de police ou autre)

![Zone 1](https://user-images.githubusercontent.com/80490183/217963527-4be37c07-4070-41a2-bbdf-23b75bf2ee78.jpg)
![zone 2](https://user-images.githubusercontent.com/80490183/217963535-cb5e74b1-4d08-41be-9d63-88ac4829f209.jpg)

**Comment by pijalu** [comment]
on muaddib

**Comment by crealan** [comment]
![Capture d'écran 2023-12-19 214340](https://github.com/pijalu/creaves/assets/80490183/dc650367-f3d8-4ac0-9d70-ffbf98452b8d)

**Comment by crealan** [comment]
Comment peut on mettre en évidence les animaux qui sont dans des zones externe au centre? 
Peut on changer la couleur du bouton avec le numéro? ou afficher un logo ou autre sur l'ensemble des vues.

(Les zones externe au centre doivent clairement être identifiée (différence de couleurs de police ou autre))

**Comment by crealan** [comment]
Dans rapports instantané ajouter les colonnes zone et cage  (https://creaves.muaddib.net/registersnapshot/)

**Comment by crealan** [comment]
Mettre en italique les onglets des zones externes au centre
