### ISSUE TITLE
Mettre à jour la table espèce

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#143]
Ajouter des colonnes et mettre a jour les données de la table species.
[Liste especes 271123 - Liste espèces.csv]
(https://github.com/pijalu/creaves/files/13479304/Liste.especes.271123.-.Liste.especes.csv)

Ajouter un order by ASC: classe, ordre, famille, species

**Comment by pijalu** [comment]
nota:
Duplicate species: 
Alauda alpestris
Anas platyrhynchos domesticus
Calidris acuminata

**Comment by crealan** [comment]
[Liste espèces CREAVES APP 101223.xlsx](https://github.com/pijalu/creaves/files/13629452/Liste.especes.CREAVES.APP.101223.xlsx)

Liste mise à jour
