### ISSUE TITLE
Liste medoc

### ISSUE THREAD

**Issue by pijalu** [pijalu/creaves#19]
Un excel avec la liste medoc / poso - au moins un debut pour pouvoir faire un seed de la base de données

**Comment by crealan** [comment]
ok

**Comment by crealan** [comment]
la poso est selon le type d'animal 
donc meme medoc poso differentes pour rapaces, herisson ou rongeurs par exemple.

**Comment by crealan** [comment]
ajouter un champ remarque en plus par medoc

**Comment by pijalu** [comment]
propose un template et comment l'utilisé...

**Comment by crealan** [comment]
liste envoyée sur messenger car le fichier passe pas ici

**Comment by pijalu** [comment]
La liste
[Liste-médoc.zip](https://github.com/pijalu/creaves/files/6159872/Liste-medoc.zip)
