### ISSUE TITLE
Afficher la date d'entrée!

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#2]
Afficher la date d'entrée dans la vue animal

**Comment by pijalu** [comment]
Quand tu ouvres un ticket - un petit peu d'explication/screenshot sur "la vue" est un plus car "la vue" peut etre
![image](https://user-images.githubusercontent.com/1093797/111193950-04276000-85bb-11eb-85ba-2521de2da574.png)

qui a la date d'entrée ;)

**Comment by crealan** [comment]
Tu es difficile 😂

**Comment by crealan** [comment]
![Capture d’écran de 2021-03-15 20-56-48](https://user-images.githubusercontent.com/80490183/111213521-1dd3a200-85d1-11eb-8433-c1aa33c58d35.png)
