### ISSUE TITLE
fiche km

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#20]

**Comment by pijalu** [comment]
Tu peux me filer la doc sur l'ecran - je ne la trouve pas :(
(sans doute passé dans messenger mais perdu depuis)

**Comment by crealan** [comment]
https://forms.gle/GFm6F8Q5yguD7SfJ8

**Comment by crealan** [comment]
Il faut pouvoir faire un relever des kms par bénévole pour les régler

Le mer. 24 mars 2021 à 10:56, Alan Gilson ***@***.***> a
écrit :
