### ISSUE TITLE
retour automatique sur general en activant l'édétion

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#30]
En activant l'édition dans la nav animal en poussant sur le crayon un retour automatique çe fait vers l'écran general  

https://creaves.muaddib.net/animals/9#nav-discovery
https://creaves.muaddib.net/animals/9#nav-intake
https://creaves.muaddib.net/animals/9#nav-care

![image](https://user-images.githubusercontent.com/80490183/111708423-1c5edf80-8846-11eb-8955-c7a76e6d73ac.png)

![image](https://user-images.githubusercontent.com/80490183/111708527-503a0500-8846-11eb-8e04-e9905c08c5a3.png)

**Comment by crealan** [comment]
Cela est esser déroutant et genère des clics inutiles!

**Comment by pijalu** [comment]
Pas un bug.. on edit pas un tab mais un animal - postlive
