### ISSUE TITLE
nouvel page d'Accueil

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#31]
creer un accueil avec 2 vue possible un tri par type et espece et un tri selon l'emplacement et le numéro de cage, afficher uniquement les animaux encore sur le centre.

![image](https://user-images.githubusercontent.com/80490183/111710715-7b265800-884a-11eb-8cfa-06013e2b93c8.png)

![image](https://user-images.githubusercontent.com/80490183/111711455-03592d00-884c-11eb-9058-28ddc5675f00.png)

![image](https://user-images.githubusercontent.com/80490183/111711882-e96c1a00-884c-11eb-961d-27c299d0a96b.png)

**Comment by crealan** [comment]
jalon à toi de voir

**Comment by pijalu** [comment]
Par emplacement: C'est quoi le rationel ?

**Comment by crealan** [comment]
> Par emplacement: C'est quoi le rationel?

il y en as pas pour l'instant nous avons prévu que le numéro de cage

**Comment by pijalu** [comment]
ok
Alors post-golive - et ca va demender un peu plus d'analyse :p

**Comment by crealan** [comment]
lettre et numéro ex: VI01, SDS12, REV35, ...

**Comment by crealan** [comment]
c'était ton idée de les affiché par emplacement :-)

**Comment by pijalu** [comment]
Oui mais ici tu arrives avec des zones et consort.... qui demande aussi des ecrans et methode de gestions :D
(et les liens "cage => zone")
L'idee de depart etait d'utiliser des "groupe" de cage (1-10, 11-20,...)

**Comment by crealan** [comment]
zone ou groupe de cage ses pareil 
cage 1-20 salle de soins
21-37 revalidation
41-55 quarantene
ou via le prefique en lettre! ( VI01, SDS12, REV35)
