### ISSUE TITLE
traduction

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#39]
traduire matin midi et soir dans l'encodage d'un traitement! 
il est mis nombre au lieu de numéro sur la vue accueil ? 

![image](https://user-images.githubusercontent.com/80490183/112055634-65b97280-8b57-11eb-9853-d70bd0ab894a.png)

![image](https://user-images.githubusercontent.com/80490183/112055742-84b80480-8b57-11eb-9695-cd52d2b434ea.png)

**Comment by crealan** [comment]
toujours en anglais!

**Comment by pijalu** [comment]
peut-etre! que! fixé! ne! veux! pas! dire! releaser!
ಠ_ಠ
