### ISSUE TITLE
la numérotation

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#5]
Présision la numérotation doit ce zéroter aux 01 Janvier !!!

**Comment by pijalu** [comment]
Attention - ici d'un point de vue fonctionel cela n'est pas correcte: Tu n'as pas la garantie d'unicité !!!
Quel est ta logique ici ?

**Comment by pijalu** [comment]
Reouvre si besoin

**Comment by crealan** [comment]
Présision la numérotation doit ce zéroter aux 01 Janvier !!! la numérotation doit être annuel le premier animal qui rentre au centre en Janvier doit avoir le numéro 1 comme une logique de facturation ou tout les ans sur retombe à 1

**Comment by crealan** [comment]
![image](https://user-images.githubusercontent.com/80490183/111294248-68453500-864a-11eb-9302-07fc0aa27cd1.png)

**Comment by crealan** [comment]
![image](https://user-images.githubusercontent.com/80490183/111309879-acd9cc00-865c-11eb-8fef-69ef448c79ab.png)

**Comment by crealan** [comment]
![image](https://user-images.githubusercontent.com/80490183/111309957-c549e680-865c-11eb-953d-76764b2c0f6f.png)
