### ISSUE TITLE
traduire les messages 

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#56]
![image](https://user-images.githubusercontent.com/80490183/112736933-d943f100-8f56-11eb-9820-c6182dfa47a7.png)
![image](https://user-images.githubusercontent.com/80490183/112736938-e660e000-8f56-11eb-90f8-513566015fc1.png)
![image](https://user-images.githubusercontent.com/80490183/112736943-f2e53880-8f56-11eb-9af9-d75b1e990a92.png)
![image](https://user-images.githubusercontent.com/80490183/112736954-fd9fcd80-8f56-11eb-90d5-7484c1fc509b.png)

**Comment by crealan** [comment]
![image](https://user-images.githubusercontent.com/80490183/112736985-363fa700-8f57-11eb-86ad-c79daf63470b.png)

**Comment by pijalu** [comment]
![image](https://user-images.githubusercontent.com/1093797/112737117-4c9a3280-8f58-11eb-9b79-f7fb31c20000.png)
