### ISSUE TITLE
griser les soins prévu pour une date futur

### ISSUE THREAD

**Issue by crealan** [pijalu/creaves#86]

**Comment by crealan** [comment]
les traitements c'est bien mais les oins aussi ;-)  https://creaves.muaddib.net/animals/289#nav-care 

![image](https://user-images.githubusercontent.com/80490183/118189508-29f9a580-b442-11eb-8b02-ba88eb8ab865.png)

**Comment by pijalu** [comment]
Un soin n'est pas fait dans le futur :|
